spring:
  application:
    name: SpringSecurity
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: rootP
  jpa:
    hibernate:
      ddl-auto: update
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 5 minutes
    refreshTokenExpiration: 86400 # 1 day